### ISSUE TITLE
Where is the main program？

### ISSUE THREAD

**Issue by Ealaine** [HuyanHuang/Robust-Low-rank-Tensor-Ring-Completion#3]

**Comment by HuyanHuang** [comment]
Please enter the Reproduce folder.

**Comment by Ealaine** [comment]
sorry，the code of this project requires the size of the input image is [256,256,3],but I want to use another color picture that has diffierent shape[256,481,3].One method is crop the picture to [256,256,3],but the result is not well, the PSNR vector of TTNN is [15.08,16.4652,18.8845],even if I changed other pictures,but use the data of this project,the result is well.Can you give me some suggestions?

**Comment by HuyanHuang** [comment]
Hi, Ealaine, a common trick frequently used in tensor completion is to
resize, which requires the size to be decomposable. For instance, in this
case you can resize 481 to 480, then you end up with a new size
4-by-4-by-5-by-6, then everything goes on usually.

Best Regards,
Huyan

Ealaine ***@***.***>于2021年8月1日 周日下午10:44写道：
